#ifndef LAB4_H
#define LAB4_H

#include <stdint.h>
#include "soc/soc.h"

// ===== Clock/Reset control =====
#define LAB4_DPORT_PERIP_CLK_EN_REG   0x3FF0000CU
#define LAB4_DPORT_PERIP_RST_EN_REG   0x3FF0002CU
#define LAB4_DPORT_RMT_CLK_EN_BIT     BIT(9)
#define LAB4_DPORT_LEDC_CLK_EN_BIT    BIT(11)
#define LAB4_DPORT_RMT_RST_BIT        BIT(9)
#define LAB4_DPORT_LEDC_RST_BIT       BIT(11)

// ===== GPIO matrix + IOMUX =====
#define LAB4_GPIO_FUNC14_OUT_SEL_CFG_REG 0x3FF44568U
#define LAB4_GPIO_FUNC33_OUT_SEL_CFG_REG 0x3FF445B4U
#define LAB4_IO_MUX_GPIO14_REG            0x3FF49030U
#define LAB4_IO_MUX_GPIO33_REG            0x3FF4906CU
#define LAB4_GPIO_MCU_SEL_MASK            0x7U
#define LAB4_GPIO_MCU_SEL_2               0x2U
#define LAB4_GPIO_MATRIX_LEDC_FUNC        73U
#define LAB4_GPIO_MATRIX_RMT_FUNC         81U

// ===== RMT =====
#define LAB4_RMT_BASE_REG              0x3FF56000U
#define LAB4_RMT_CH0DATA_REG           0x3FF56000U
#define LAB4_RMT_CH0CONF0_REG          0x3FF56020U
#define LAB4_RMT_CH0CONF1_REG          0x3FF56024U
#define LAB4_RMT_INT_RAW_REG           0x3FF56080U
#define LAB4_RMT_INT_CLR_REG           0x3FF5608CU
#define LAB4_RMT_APB_CONF_REG          0x3FF560D0U
#define LAB4_RMT_DATA_REG(i)           (LAB4_RMT_CH0DATA_REG + ((i) * 4U))

#define LAB4_RMT_DIV_CNT_S             0U
#define LAB4_RMT_DIV_CNT_MASK          (0xFFU << LAB4_RMT_DIV_CNT_S)
#define LAB4_RMT_MEM_SIZE_CH0_S        8U
#define LAB4_RMT_MEM_SIZE_CH0_MASK     (0xFU << LAB4_RMT_MEM_SIZE_CH0_S)
#define LAB4_RMT_CARRIER_EN_CH0_BIT    BIT(6)
#define LAB4_RMT_MEM_OWNER_CH0_BIT     BIT(3)
#define LAB4_RMT_TX_CONTI_MODE_CH0_BIT BIT(1)
#define LAB4_RMT_TX_START_CH0_BIT      BIT(0)
#define LAB4_RMT_CONF_UPDATE_CH0_BIT   BIT(24)
#define LAB4_RMT_CH0_TX_END_INT_RAW_BIT BIT(0)
#define LAB4_RMT_CH0_TX_END_INT_CLR_BIT BIT(0)

// ===== LEDC =====
#define LAB4_LEDC_BASE_REG              0x3FF59000U
#define LAB4_LEDC_HSTIMER0_CONF_REG     0x3FF59000U
#define LAB4_LEDC_HSCH0_CONF0_REG       0x3FF59014U
#define LAB4_LEDC_HSCH0_HPOINT_REG      0x3FF59018U
#define LAB4_LEDC_HSCH0_DUTY_REG        0x3FF5901CU
#define LAB4_LEDC_HSCH0_CONF1_REG       0x3FF59020U
#define LAB4_LEDC_INT_RAW_REG           0x3FF590C0U
#define LAB4_LEDC_INT_CLR_REG           0x3FF590CCU

#define LAB4_LEDC_TIMER_DIV_NUM_S       4U
#define LAB4_LEDC_TIMER_DIV_NUM_MASK    (0x3FFFFU << LAB4_LEDC_TIMER_DIV_NUM_S)
#define LAB4_LEDC_TIMER_PAUSE_BIT       BIT(0)
#define LAB4_LEDC_TIMER_RST_BIT         BIT(1)
#define LAB4_LEDC_TIMER_PARA_UP_BIT     BIT(2)
#define LAB4_LEDC_TIMER_DUTY_RES_S      20U
#define LAB4_LEDC_TIMER_DUTY_RES_MASK   (0xFU << LAB4_LEDC_TIMER_DUTY_RES_S)

#define LAB4_LEDC_TIMER_SEL_CH0_S       0U
#define LAB4_LEDC_TIMER_SEL_CH0_MASK    (0x3U << LAB4_LEDC_TIMER_SEL_CH0_S)
#define LAB4_LEDC_SIG_OUT_EN_CH0_BIT    BIT(2)
#define LAB4_LEDC_PARA_UP_CH0_BIT       BIT(4)
#define LAB4_LEDC_DUTY_START_CH0_BIT    BIT(31)
#define LAB4_LEDC_TIMER0_OVF_INT_RAW_BIT BIT(0)
#define LAB4_LEDC_TIMER0_OVF_INT_CLR_BIT BIT(0)

// ===== WS2812 timing at 80 MHz (12.5 ns/tick) =====
#define LAB4_WS_T0H 32U
#define LAB4_WS_T0L 68U
#define LAB4_WS_T1H 64U
#define LAB4_WS_T1L 36U
#define LAB4_WS_RESET_US 60U

#define LAB4_NUM_LEDS 100U
#define LAB4_BITS_PER_LED 24U
#define LAB4_RMT_WORDS_PER_LED (LAB4_BITS_PER_LED + 1U)
#define LAB4_RMT_MEM_WORDS_PER_BLOCK 64U
#define LAB4_RMT_MEM_BLOCKS_CH0 8U
#define LAB4_RMT_TOTAL_WORDS (LAB4_RMT_MEM_WORDS_PER_BLOCK * LAB4_RMT_MEM_BLOCKS_CH0)
#define LAB4_RMT_MAX_LEDS_PER_TX ((LAB4_RMT_TOTAL_WORDS - 1U) / LAB4_BITS_PER_LED)

#ifdef __cplusplus
extern "C" {
#endif
void setup_RMT(void);
void setup_LEDC(void);
void update_PWM(uint32_t initial, uint32_t sample);
void transmit_led_signal(uint32_t *colors);
#ifdef __cplusplus
}
#endif

#endif